- .eslintrc.json
- .stickler.yml
- server.js
> Improvements - Logging, Search, Redirection

- .eslintrc.json
- lib/DropCache.js
- package.json
- server.js
* keep `?search=` for manual searches if people feel like it
* support multiple queries in searches, like multiple weapons, warframes, etc.
> Search Route

- lib/Route.js
- lib/routes/Drops.js
- lib/routes/PriceCheck.js
- lib/routes/Search.js
- lib/routes/Worldstate.js
- lib/routes/WorldstateData.js
- package-lock.json
- package.json
- server.js
---
**Summary (short):** move routes to modules, add route for pricecheck
---
**Mockups, screenshots, evidence:** test deployment, #4 #5 fulfillments
---
(Check one)
> Modules for routes, pricecheck route

- lib/routes/TennoTv.js
- package-lock.json
- package.json
- server.js
feat: add user history delete request
api tokens for add and update
feat: icons instead of text, hover for info
> feat: user's video history

- package-lock.json
- package.json
> chore(dependencies): Greenkeeper/warframe worldstate data 0.0.419

- package-lock.json
- package.json
> Greenkeeper/warframe worldstate data 0.0.430

- package-lock.json
- package.json
> Greenkeeper/warframe worldstate data 0.0.440

- package-lock.json
- package.json
> Greenkeeper/warframe worldstate data 0.0.443

- package-lock.json
- package.json
> Greenkeeper/warframe items 1.51.0

- package-lock.json
- package.json
> Greenkeeper/warframe items 1.58.0

- package-lock.json
- package.json
> Greenkeeper/nodemon 1.18.7

- controllers/index.js
- controllers/rss.js
- controllers/twitter.js
- lib/caches/Drops.js
- lib/caches/RSSSocketEmitter.js
- lib/caches/TwitterCache.js
- package.json
- sockets/rss.js
> clean up some parsing potential weirdness

- package.json
Pinned Colors.js to version 1.4.0
---
- Does this contain a new dependency? **Yes**
- Does this introduce opinionated data formatting or manual data entry? **NO**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **Yes**
- Have I run the linter? **Yes**
- Is is a bug fix, feature request, or enhancement? **Bug Fix**
> Pin colors version to 1.4.0

- .github/workflows/ci.yaml
- .github/workflows/release.yml
creates an automated deploy pathway for warframe-status
---
used recommended actions from https://blog.benoitblanchon.fr/github-action-run-ssh-commands/
---
You can see my addition in the release config
> chore(ci): create deploy script

- .github/workflows/release.yml
closes #12312312
---
---
- Does this contain a new dependency? **[Yes/No]**
- Does this introduce opinionated data formatting or manual data entry? **[Yes/No]**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[Yes/No]**
- Have I run the linter? **[Yes/No]**
- Is is a bug fix, feature request, or enhancement? **[Bug Fix/Feature/Enhancement/Docs/Maintenance]**
> ci: update semantic release action

- package-lock.json
- package.json
---
---
- Is is a bug fix, feature request, or enhancement? **[Feature]**
> feat: synth data image keys

- .gitignore
- src/controllers/profile.js
- src/controllers/wfinfo.js
- src/lib/hydrate.js
- src/spec/pricecheck.spec.js
- src/spec/profile.spec.js
improve authentication for arsenal programmatically
---
---
- Is is a bug fix, feature request, or enhancement? **[Enhancement]**
> fix: better auth for arsenal

- .github/workflows/ci.yaml
- .github/workflows/release.yml
- package.json
- src/controllers/data.js
- src/controllers/drops.js
- src/controllers/heartbeat.js
- src/controllers/index.js
- src/controllers/items.js
- src/controllers/pricecheck.js
- src/controllers/profile.js
- src/controllers/rivens.js
- src/controllers/rss.js
- src/controllers/twitter.js
- src/controllers/wfinfo.js
- src/controllers/worldstate.js
- src/lib/utilities.js
- src/spec/profile.spec.js
- src/spec/worldstate.spec.mjs
fixes an issue where all the consoles get weird errors
---
---
if anyone has time to test this against your own apps and make sure it still seems to work, i'd appreciate it
the only problematic part is making sure your stuff handles redirects properly
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[Yes]**
> feat: deprecate & redirect consoles

- package-lock.json
- package.json
add uk support
---
---
upgrade worldstate-data to the version with uk support
- Is is a bug fix, feature request, or enhancement? **[Feature]**
> feat(i18n): add uk locale

- package-lock.json
- package.json
update status to items w/ hildryn prime
---
---
> fix(items): bump warframe-items to latest

- src/lib/hydrate.js
add json checks for wfinfo data hydration to prevent blocking server startup
---
---
> fix(hydrate): safety checks when hydrating

- src/controllers/rivens.js
> fix: rivens domain moved

- .nvmrc
- main.js
- package-lock.json
- package.json
- src/controllers/index.js
- src/lib/addons.js
- src/lib/hydrate.js
- src/lib/settings.js
- src/socket.js
- src/spec/hooks/env.js
- src/spec/hooks/start.hook.js
- src/spec/tester.js
- src/spec/worldstate.spec.mjs
- fixes having to use the query param to cache on cloudflare/etc
- introduce more into settings, use it more heavily
- reorganize invocations to port/host, use dynamically
---
---
- Is is a bug fix, feature request, or enhancement? **[Enhancement]**
> feat: caching language header as part of key

- main.js
- package-lock.json
- package.json
- src/lib/settings.js
- more logging
- try to resolve the ip from whatever is given (hostname, etc)
- this is not ideal, given how it has to start up w/ undefined first
- crazy enough, that still works better than allowing it to get a bad value, i.e. an AAAA record.
---
---
- Does this introduce opinionated data formatting or manual data entry? **[Yes]**
> feat: allow disabling socket

- .gitignore
- package.json
- src/controllers/drops.js
- src/controllers/items.js
- src/controllers/rivens.js
- src/lib/addons.js
- src/lib/caches/Drops.js
- src/lib/caches/Items.js
- src/lib/caches/Rivens.js
- src/lib/hydrate.js
- src/lib/logger.js
closes #1301
- rewrite items, rivens, drops fetches
- create pattern for more caches
- TODOs documented for future caches
to rewrite some of the other fetches, i'll need to rewrite worldstate-emitter w/ fetch & node 18 (probably something ssl-related in json-fetch-cache)
blocks #1305 
blocks #1302 
---
start it up
---
> fix: loading the twitch token for profile fetches

- package-lock.json
- package.json
- src/controllers/worldstate.js
- src/lib/utilities.js
- src/sockets/index.js
- src/spec/profile.spec.js
- src/spec/worldstate.spec.js
N/A, just routine upgrades
---
---
> fix: use esm worldstate-emitter

- main.js
- src/lib/addons.js
Scale instances per CPU
---
---
- Does this contain a new dependency? **Yes**
- Does this introduce opinionated data formatting or manual data entry? **No**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **Yes**
- Have I run the linter? **Yes**
- Is is a bug fix, feature request, or enhancement? **Enhancement**
> feat: use `cluster` to scale per cpu

- main.js
- package-lock.json
- package.json
fix issues from v1.14.0
---
---
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[Yes]**
> fix: smarter clustering

- main.js
american mathing
---
Divide the number of cores, don't modulo/rem the number of cores
---
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[Yes]**
> fix: divide, not mod

- package-lock.json
- src/app.js
- src/lib/addons.js
- src/lib/instrument.js
weird sentry on v2.0.7
---
---
> fix: load sentry first

- package-lock.json
- package.json
async? 
@KingPrimes please give this a shot locally on websockets if you've got a chance
---
---
- Is is a bug fix, feature request, or enhancement? **[Enhancement]**
> feat: update parser & emitter to latest async

- package-lock.json
- package.json
> fix: update profile-parser to fix timeouts
